In [1]:
import pandas as pd

my_data = [4,5,6]
arr = pd.array(my_data)
type(arr)

pandas.arrays.IntegerArray

In [2]:
# Series - tek boyutlu
s = pd.Series([1, 2, 3], index=['a', 'b', 'c'])

# DataFrame - iki boyutlu tablo
df = pd.DataFrame({
    'isim': ['Ali', 'Ayşe', 'Veli'],
    'yas': [25, 30, 35]
})
df

   isim  yas
0   Ali   25
1  Ayşe   30
2  Veli   35

In [ ]:
# Veri Okuma/Yazma
# df.to_csv('cikti.csv', index=False)

In [ ]:
# my_csv = pd.read_csv('cikti.csv')
# my_csv

In [ ]:
df.head()       # ilk 5 satır
df.tail()       # son 5 satır
df.info()       # sütun tipleri, null sayısı
df.describe()   # istatistiksel özet
df.shape        # (satır, sütun)
df.columns      # sütun isimleri
df.dtypes       # veri tipleri

In [10]:
df['yas']                    # tek sütun
df[['isim', 'yas']]          # birden fazla sütun
df.loc[0]                    # label ile satır
df.iloc[1]                   # index numarasıyla satır
df[df['yas'] > 25]           # koşullu filtreleme
df.query('yas > 25')         # aynı işlem, farklı sözdizim

   isim  yas
1  Ayşe   30
2  Veli   35

In [ ]:
# Eksik Veri
df.isnull().sum()            # her sütunda kaç NaN var
df.dropna()                  # NaN olan satırları sil
df.fillna(0)                 # NaN'ları doldur

In [ ]:
df.groupby('companies')[['sales']].sum()

In [ ]:
df.groupby('companies')['sales'].sum()      # total sales per company
df.groupby('companies')['sales'].mean()     # average sales per company
df.groupby('companies')['sales'].count()    # number of records per company
df.groupby('companies')['sales'].agg(['sum', 'mean', 'count'])  # multiple at once

In [ ]:
df[df['marital']=='married' and df['balance']>2500]